# hyper-parameters settings
Train:
  learning_rate: 0.001
  lr_steps: [40, 45]
  num_epochs: 50
  test_interval: 5
  img_size: 448
  burn_in: 100
  batch_size: 16
  num_boxes: 2
  size_grid_cell: 14
  num_classes: 20
  lambda_coord: 5
  lambda_noobj: 0.5
  with_difficult: False
  do_augmentation: True

Test:
  conf_thresh: 0.1
  iou_thresh: 0.5
  nms_thresh: 0.45
