# hyper-parameters settings
Train:
  learning_rate: 0.001
  burn_in: 1000
  lr_steps: [90, 120]
  num_epochs: 150
  test_interval: 1
  img_size: 448
  batch_size: 16
  num_boxes: 2
  size_grid_cell: 7
  num_classes: 20
  lambda_coord: 5
  lambda_noobj: 0.5
  num_workers: 4
  with_difficult: False
  do_augmentation: True

Test:
  iou_thresh: 0.5
  conf_thresh: 0.005
  nms_thresh: 0.45
